# Generated by Django 4.0.4 on 2022-05-18 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 18, 10, 58, 4, 789189, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
